AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  bedrock_application

  Sample SAM Template for bedrock_application

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    LoggingConfig:
      LogFormat: JSON

Resources:
  BedrockLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Environment:
        Variables:
          BEDROCK_MODEL_ID: "amazon.titan-image-generator-v1"
          S3_BUCKET_NAME: "pgr301-couch-explorers"
          AWS_REGION: "eu-west-1"
      Policies:
        - Statement:
            - Effect: Allow
              Action: bedrock:InvokeModel
              Resource: arn:aws:bedrock:us-east-1:244530008913:foundation-model/amazon.titan-image-generator-v1
            - Effect: Allow
              Action:
                - s3:PutObject
              Resource: arn:aws:s3:::pgr301-couch-explorers/2/generated_images/*
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: post

Outputs:
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  BedrockLambdaFunction:
    Description: Bedrock Lambda Function ARN
    Value: !GetAtt BedrockLambdaFunction.Arn
  BedrockLambdaFunctionRole:
    Description: Implicit IAM Role created for BedrockLambdaFunction
    Value: !GetAtt BedrockLambdaFunctionRole.Arn
