name: on push to main build and deploy the bedrock application
on:
    push:
        branches:
            - main
    
    workflow_dispatch:
            
            
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
        
            # checkout repository
            - name: checkout repository
              uses: actions/checkout@v3
              
            # setup python
            - name: setup python 3.8
              uses: actions/setup-python@v4
              with:
                python-version: '3.8'
            
            # confirm aws cli
            - name: Verify AWS CLI Version
              run: |
                aws --version
                
           # Verify SAM CLI Version
           - name: Verify SAM CLI Version
             run: |
              sam --version
                
            # configure aws credentials
            - name: configure aws credentials
              uses: aws-actions/configure-aws-credentials@v3
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}
            
            # cache pip dependecies
            - name: cache pip dependecies
              uses: actions/cache@v3
              with:
                path: ~/.cache/pip
                key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
                restore-keys: |
                    ${{ runner.os }}-pip-
            
            # install dependencies
            - name: install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                
            # build sam application
            - name: build sam application
              run: |
                sam build
            
            # deploy sam application
            - name: deploy sam application
              run: |
                sam deploy \
                --no-confirm-changeset \
                --no-fail-on-empty-changeset \
                --stack-name ${{ secrets.STACK_NAME }} \
                --s3-bucket ${{ secrets.S3_BUCKET }} \
                --capabilities CAPABILITY_IAM \
                --region ${{ secrets.AWS_REGION }}