name: on push to main build and deploy the bedrock application
on:
    push:
        branches:
            - main
    
    workflow_dispatch:
            
            
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            # checkout repository
            - name: checkout repository
              uses: actions/checkout@v3
              
            # setup python
            - name: setup python 3.8
              uses: actions/setup-python@v4
              with:
                python-version: '3.8'
                
            # configure aws credentials
            - name: configure aws credentials
              uses: aws-actions/configure-aws-credentials@v3
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.REGION_NAME }}
            
            # cache pip dependecies
            - name: cache pip dependecies
              uses: actions/cache@v3
              with:
                path: ~/.cache/pip
                key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
                restore-keys: |
                    ${{ runner.os }}-pip-
            
            # install dependencies
            - name: install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r bedrock_sam/bedrock_application/hello_world/requirements.txt
                
            # build sam application
            - name: build sam application
              run: |
                sam build
              working-directory: bedrock_sam/bedrock_application/
              
            - name: List Environment Variables
              run: |
                printenv | sort
                
            # Deploy SAM Application with Debugging
            - name: Deploy SAM Application with Debugging
              run: |
                echo "Before unsetting:"
                echo "AWS_REGION=${AWS_REGION}"
                echo "AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}"
                
                unset AWS_REGION
                unset AWS_DEFAULT_REGION
                
                echo "After unsetting:"
                echo "AWS_REGION=${AWS_REGION}"
                echo "AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}"
                
                sam deploy \
                  --no-confirm-changeset \
                  --no-fail-on-empty-changeset \
                  --stack-name ${{ secrets.STACK_NAME }} \
                  --capabilities CAPABILITY_IAM \
                  --region ${{ secrets.REGION_NAME }}
              working-directory: bedrock_sam/bedrock_application/