name: Build and Push Docker Image to DockerHub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: primussy/devops243b:latest

      - name: Tag Docker Image
        run: |
          IMAGE_NAME=primussy/devops243b
          LATEST_TAG=latest
          COMMIT_SHA=${GITHUB_SHA::7}
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          BRANCH_NAME=${BRANCH_NAME//\//-}
          docker tag $IMAGE_NAME:$LATEST_TAG $IMAGE_NAME:${COMMIT_SHA}
          docker tag $IMAGE_NAME:$LATEST_TAG $IMAGE_NAME:${BRANCH_NAME}
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "COMMIT_SHA_TAG=${COMMIT_SHA}" >> $GITHUB_ENV
          echo "BRANCH_TAG=${BRANCH_NAME}" >> $GITHUB_ENV

      - name: Push Docker Image with Tags
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ env.COMMIT_SHA_TAG }}
            ${{ env.IMAGE_NAME }}:${{ env.BRANCH_TAG }}
